### ISSUE TITLE
Discord Token Expires after 24 hours

### ISSUE THREAD

**Issue by DrRayZor** [gtrxAC/discord-j2me#27]
Is there a way to stay logged in to the app? I have to copy a new token from the browser into the app every 24 hours, which is quite tedious. 
pls Help!

**Comment by gtrxAC** [comment]
Discord tokens generally do not expire unless you change your account's password. Most people I know have used the same token since they first started using the app. I've never had to change my login token either. I don't know why it expires every 24 hours for you - maybe it's a new Discord security measure for new accounts, or accounts which are not logged into multiple devices, or something.
Most (if not all) custom Discord clients require a token for logging in, so there isn't really any fix for this. You can try changing your password or trying with another account though.
